# http://about.travis-ci.org/docs/user/build-configuration/
language: php

php:
    - 5.2
    - 5.3
    - 5.4

notifications:
    email:
        - system128@gmail.com

# compile
before_script:
    - cd src
    - phpize
    - ./configure
    - make

# test
script:
    - pear run-tests --cgi=php-cgi tests/*.phpt

